# Generated by Django 4.2.7 on 2024-01-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_additional_info_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alley',
            field=models.CharField(max_length=50, null=True, verbose_name='Alley'),
        ),
        migrations.AddField(
            model_name='address',
            name='no',
            field=models.CharField(default=0, max_length=50, verbose_name='NO'),
        ),
        migrations.AddField(
            model_name='address',
            name='unit_number',
            field=models.CharField(default=0, max_length=50, verbose_name='Unit Number'),
        ),
    ]
