# Generated by Django 4.2.7 on 2024-01-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_customer_user_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='addresses',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='users.address', verbose_name='Addresses'),
        ),
    ]
