# Generated by Django 4.2.7 on 2024-01-24 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Enter your phone number.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_IR_phone_number', message='Phone number must be start with +98 or 0 in IR format.', regex='^(\\+98|0)?9\\d{9}$')], verbose_name='Phone'),
        ),
    ]
