# Generated by Django 4.2.7 on 2024-01-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_employee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_staff',
            new_name='is_operator',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_customer_support',
            new_name='is_viewer',
        ),
    ]
