# Generated by Django 4.2.7 on 2024-01-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_is_staff_employee_is_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_operator',
            field=models.BooleanField(default=False, verbose_name='Is Operator'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_viewer',
            field=models.BooleanField(default=False, verbose_name='Is Viewer'),
        ),
    ]
