# Generated by Django 4.2.7 on 2024-01-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagess', '0002_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Image'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Images', 'verbose_name_plural': 'Product Images'},
        ),
    ]
