# Generated by Django 4.2.7 on 2024-01-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagess', '0003_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductImageAlbum',
        ),
        migrations.AlterModelOptions(
            name='productimagealbum',
            options={'verbose_name': 'Product Images Album', 'verbose_name_plural': 'Product Images Album'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Image'},
        ),
    ]
