# Generated by Django 4.2 on 2024-02-26 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('is_deleted', models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('is_deleted', models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='category_images/', verbose_name='Image')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='products.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('is_deleted', models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20, verbose_name='Discount Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Amount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('is_deleted', models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('is_deleted', models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='products.discount', verbose_name='Discount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'custom_product_category',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(through='products.ProductCategory', to='products.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('is_deleted', models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted')),
                ('content', models.TextField(verbose_name='Content')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentChildComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('is_deleted', models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted')),
                ('depth', models.IntegerField(verbose_name='Depth')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='products.comment', verbose_name='Child')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_comments', to='products.comment', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Parent-Child Comment',
                'verbose_name_plural': 'Parent-Child Comments',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
