# Generated by Django 4.2.7 on 2024-01-13 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentchildcomment',
            options={'verbose_name': 'Parent-Child Comment', 'verbose_name_plural': 'Parent-Child Comments'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='products.category', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Amount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='parentchildcomment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='products.comment', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='parentchildcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='parentchildcomment',
            name='depth',
            field=models.IntegerField(verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='parentchildcomment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='parentchildcomment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted'),
        ),
        migrations.AlterField(
            model_name='parentchildcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_comments', to='products.comment', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='parentchildcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(through='products.ProductCategory', to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at this time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='products.discount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Status is deleted', verbose_name='Status: Deleted'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified at this time', verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Valid To'),
        ),
    ]
